name: Feature request
description: Propose an enhancement
labels: [feature]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem should this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What behavior or API do you propose?
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope and impact
      description: Risks, trade-offs, and compatibility notes
